### ISSUE TITLE
Incorrect cad for kraken

### ISSUE THREAD

**Issue by Jbori347** [bigtreetech/BIGTREETECH-Kraken#1]
The kraken step file does not match the actual board.

**Comment by jimberg98** [comment]
The dimensions in the size image are also confusing. The top width dimension says 200.3 mm while the bottom says 200 mm. The left height dimension says 113.03 mm and the right dimension says 113.42. Are those correct?

**Comment by BTTJUSTIN** [comment]
The documentation has been updated. Thanks again for pointing out the issue.
