### ISSUE TITLE
TMC5160 or TMC2160?

### ISSUE THREAD

**Issue by tescolopio** [bigtreetech/BIGTREETECH-Kraken#11]
In the documentation you have labeled the stepper drivers as TMC2160 which doesn't match up with the configuration of TMC 5160. This is everywhere in the manual and marlin setup documentation. You can understand my confusion because I cannot find TMC5160 in the klipper documentation but... I can find a stepper drive TMC2160 developed by MKS.

Can you please clarify and correct in either case?

Thanks!

![Screenshot from 2024-03-30 16-25-31](https://github.com/bigtreetech/BIGTREETECH-Kraken/assets/162474789/601cc8c9-f611-4c66-bb1f-e952d1f7f302)
![Screenshot from 2024-03-30 16-25-10](https://github.com/bigtreetech/BIGTREETECH-Kraken/assets/162474789/9f07272e-d488-4c2e-b4f1-ccccbbf41305)

**Comment by tescolopio** [comment]
Also, you have it listed as 2160 EVERYWHERE. Amazon, your website, advertising. But also it says 5160. Look at this picture. At the top it says 2160. Bottom says 5160. Thoughts?
![Screenshot from 2024-03-30 16-41-43](https://github.com/bigtreetech/BIGTREETECH-Kraken/assets/162474789/e0a8c488-e1fb-43b8-b3d3-842912bd3d7c)
![Screenshot from 2024-03-30 16-25-50](https://github.com/bigtreetech/BIGTREETECH-Kraken/assets/162474789/db9e172d-f56a-4d89-a6e9-9d66881d60dd)

**Comment by tescolopio** [comment]
I realize that the architecture of the steppers are indeed TMC2160A-TA. I looked at the schematic. My question, to which I created a ticket with klipper with for as well, is do we need a specific config reference for the TMC2160 or is using the 5160 fine? Does this matter over time? Are there new features offered through the 2160 that should be configurable?

**Comment by 5jvm0u4** [comment]
I read form somewhere that TMC2160 has the same functionality and pinout as TMC5160, the only difference is TMC5160 has it's own built-in accel-decel control in one specific mode.

**Comment by 5jvm0u4** [comment]
I read it here, and I'm searching the same question as you are.
https://www.cnblogs.com/xing2/p/17457821.html

**Comment by looxonline** [comment]
The drivers are functionally (and internally) identical. The 2160 simply has a part of the silicon that is not used in 3D printing untested and deactivated.

**Comment by tescolopio** [comment]
Thanks for replying all. Much appreciated. I have been running with the 5160 drivers defined in my klipper and have had no issues.
