### ISSUE TITLE
How to connect Kraken to CB2

### ISSUE THREAD

**Issue by azaneff** [bigtreetech/BIGTREETECH-Kraken#16]
Hi, cant connect BTT Kraken + CB2 to klipper. Error: mcu 'mcu': Unable to connect.
I installed a cable between the SBC and the CB2, and entered the serial number of the mcu in the printer.cfg. I'm wrong somewhere, but I don't know where. I'm asking for help.

**Comment by looxonline** [comment]
Hi. We don't use github as a support tool as it is not optimal for this purpose. We use it for customers to report firmware or hardware issues.

You will get great support from our facebook user group or from many of the discord user groups. If you would like to speak to a support technician then we encourage the use of the ticket tool which allows us to ensure that we follow up: https://biqu.equipment/pages/technical-support
