### ISSUE TITLE
reports error: DRV_STATUS: 001f5008 sg_result=8 s2vsa=1(ShortToSupply_A!)

### ISSUE THREAD

**Issue by evilskinny** [bigtreetech/BIGTREETECH-Kraken#2]
running a voron trident.  I kept getting the above error message for Z1 so i switched it from motor port 6 to 8.  Now im getting the same error for Z2 which is on motor port 7.  any ideas.  here is the complete klipper error.
![Capture](https://github.com/bigtreetech/BIGTREETECH-Kraken/assets/58640343/86b222bd-ed04-4de7-9bcb-56fe3bfa938b)

**Comment by looxonline** [comment]
> running a voron trident. I kept getting the above error message for Z1 so i switched it from motor port 6 to 8. Now im getting the same error for Z2 which is on motor port 7. any ideas. here is the complete klipper error. ![Capture](https://private-user-images.githubusercontent.com/58640343/296527708-86b222bd-ed04-4de7-9bcb-56fe3bfa938b.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMTI5NTksIm5iZiI6MTcxMTExMjY1OSwicGF0aCI6Ii81ODY0MDM0My8yOTY1Mjc3MDgtODZiMjIyYmQtZWQwNC00ZGU3LTliY2ItNTZmZTNiZmE5MzhiLkpQRz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDEzMDQxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3NWY1MmI4ZDQ0ZTU3NzQwNzI3YmI0N2I2Njg1NmU3Yjc0Y2FiZDZkMmFlYWZkMDk4OWViMTZhYjEyYjdkMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t3jIgAJNlaXnkTg5RQz1dW7DRd9kVZAdNniBxYK4w38)

We have seen this before when someone was using the incorrect motor sense resistor value and the driver was trying to output 4 x the required current in order to get the needed feedback signal. This triggered the supply short warning. Check your sense values.

**Comment by BTTJUSTIN** [comment]
Thanks for reaching out. Our support team does not operate using the GitHub
platform but we would be happy to help you via email based ticketing system. Please visit
https://biqu.equipment/pages/technical-support and submit a ticket and we will be in touch with you soon.
