### ISSUE TITLE
Adding the board environment & firmware for Marlin?

### ISSUE THREAD

**Issue by BoothyBoothy** [bigtreetech/BIGTREETECH-Kraken#4]
Is there any plans to add Marlin firmware for the Kraken?

Would like to utilise the increased driver power options with Nema 23 motors on my CNC router.

Thanks in advance

Boothy

**Comment by thisiskeithb** [comment]
Support was added last month: https://github.com/MarlinFirmware/Marlin/commit/c485f513d70acc838b7a1554c955fdaf5ef3df7f

Grab the latest [`bugfix-2.1.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.1.x.zip) and use `BOARD_BTT_KRAKEN_V1_0`.

**Comment by BoothyBoothy** [comment]
Yes Thank You for the Heads Up

**Comment by thisiskeithb** [comment]
@BTTJUSTIN: The Kraken has been added to upstream Marlin so this issue can be closed.
